pccp/frontend/views.py
from flask import Blueprint, render_template, current_app, request, flash, \
        url_for, redirect, session, abort, g
from sqlalchemy import and_


from pccp.extensions import db
from pccp.frontend.models import Projet, IndexContent
from pccp.utils.bbcode import parse_bbcode

frontend = Blueprint('frontend', __name__)


@frontend.route('/')
def home():
    projets = Projet.query.filter(and_(
                Projet.is_visible == True,
                Projet.is_archive == False
            )).order_by(db.desc(Projet.promo)).all()
    ic = IndexContent.query.get(1)
    if ic is None:
        ic = IndexContent()
    return render_template('index.html', projets=projets, content=ic)

@frontend.route('/projet/<string:slug>')
def projet(slug):
    p = Projet.query.filter_by(slug=slug).first()
    print(p.name)
    if not p.is_visible:
        redirect("frontend.home")

    p.content = parse_bbcode(p.content)

    return render_template(
        'frontend/projet.html',
        projet=p
    )

templates/index.html
{% extends  "layouts/base.html" %}

{% block title %}PC Coup d'Pouce{% endblock %}
{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/frontend/index.css') }}"/>
{% endblock %}
{% block js %}
<script type="text/javascript" src="{{ url_for('static', filename='js/frontend/index.js') }}"></script>
{% endblock %}

{% block content%}
<main class="main">
    <section class="carousel" id="carousel">
        {% for projet in projets %}
            {% if loop.index0 == 0%}
            <div class="slide slide-active">
            {% else %}
            <div class="slide">
            {% endif %}
                <div class="slide-text-container">
                    <div class="slide-text slide-project">PROJET</div>
                    <div class="slide-text slide-title">{{ projet.name | upper }}</div>
                    <div class="slide-text slide-subtitle">{{ projet.courte_description}}</div>
                    <a class="slide-button" href="{{ url_for('frontend.projet', slug=projet.slug) }}">En savoir plus</a>
                </div>
                <div class="slide-img">
                    <img src="{{ url_for('static', filename='img/projets/' + projet.slug + '/' + projet.slug + '_cover.jpg') }}" alt="Photo {{ projet.name}}">
                </div>
            </div>
        {% endfor %}
        <div class="dots" id="dots-container">
            {% for projet in projets %}
                {% if loop.index0 == 0 %}
                <span class="dot dot-active"></span>
                {% else %}
                <span class="dot"></span>
                {% endif %}
            {% endfor %}
        </div>
    </section>
    <div class="container">
        <section class="bienvenue main-section bbcode" id="about">
            {{ content.bienvenue | bbcode | safe}}
        </section>
        <section class="keypoint-container main-section">
            <div class="keypoint">
                <div class="keypoint-icon"><i class="fa {{ content.keypoint1_icon }}"></i></div>
                <div class="keypoint-title">{{ content.keypoint1_title }}</div>
                <div class="keypoint-text">{{ content.keypoint1_content | bbcode | safe }}</div>
            </div>
            <div class="keypoint">
                <div class="keypoint-icon"><i class="fa {{ content.keypoint2_icon }}"></i></div>
                <div class="keypoint-title">{{ content.keypoint2_title }}</div>
                <div class="keypoint-text">{{ content.keypoint2_content | bbcode | safe }}</div>
            </div>
            <div class="keypoint">
                <div class="keypoint-icon"><i class="fa {{ content.keypoint3_icon }}"></i></div>
                <div class="keypoint-title">{{ content.keypoint3_title }}</div>
                <div class="keypoint-text">{{ content.keypoint3_content | bbcode | safe }}</div>
            </div>
            <div class="keypoint">
                <div class="keypoint-icon"><i class="fa {{ content.keypoint4_icon }}"></i></div>
                <div class="keypoint-title">{{ content.keypoint4_title }}</div>
                <div class="keypoint-text">{{ content.keypoint4_content | bbcode | safe }}</div>
            </div>
        </section>
    </div>
    <section class="don main-section">
        <div class="container don-container" id="don">
            <h2>FAÎTES UN <span class="orange">DON</span></h2>
            <div class="don-flex-container">
                <div class="don-text">
                    {{ content.don | bbcode | safe}}
                </div>
                <div class="don-button">
                    <a href="#">FAIRE UN DON</a>
                </div>
            </div>
        </div>
    </section>
    <div class="container">
        <section class="projets main-section" id="projets">
            <h2>NOS PROJETS</h2>
            <div class="projets-subtitle">
                Découvrez nos projets en cours ou terminés.
            </div>
            <div class="projets-tiles-container">
                {% for projet in projets %}
                <a class="projets-tile" href="{{ url_for('frontend.projet', slug=projet.slug) }}">
                    <div class="projets-tile-img">
                        <img src="{{ url_for('static', filename='img/projets/' + projet.slug + '/' + projet.slug + '_thumbnail.jpg') }}" alt="Image projet.slug">
                    </div>
                    <div class="projets-description">{{ projet.courte_description }}</div>
                    <div class="projets-location"><i class="fas fa-map-marker-alt"></i> {{ projet.location }}</div>
                </a>
                {% endfor %}
            </div>
        </section>
    </div>
    <section class="chiffres main-section">
        <div class="container">
            <h2>PC COUP D'POUCE EN QUELQUES CHIFFRES</h2>
            <div class="chiffres-subtitle">Pour vous donner une petite idée de ce que nous faisons à PC Coup d'Pouce , découvrez notre association en chiffres.</div>
            <div class="chiffres-data-container">
                <div class="chiffres-data">
                    <div class="chiffres-logo">
                        <i class="fa {{ content.chiffres1_icon }}"></i>
                    </div>
                    <div class="chiffres-number">
                        {{ content.chiffres1_title }}
                    </div>
                    <div class="chiffres-text">
                        {{ content.chiffres1_content }}
                    </div>
                </div>
                <div class="chiffres-data">
                    <div class="chiffres-logo">
                        <i class="fa {{ content.chiffres2_icon }}"></i>
                    </div>
                    <div class="chiffres-number">
                        {{ content.chiffres2_title }}
                    </div>
                    <div class="chiffres-text">
                        {{ content.chiffres2_content }}
                    </div>
                </div>
                <div class="chiffres-data">
                    <div class="chiffres-logo">
                        <i class="fa {{ content.chiffres3_icon }}"></i>
                    </div>
                    <div class="chiffres-number">
                        {{ content.chiffres3_title }}
                    </div>
                    <div class="chiffres-text">
                        {{ content.chiffres3_content }}
                    </div>
                </div>
                <div class="chiffres-data">
                    <div class="chiffres-logo">
                        <i class="fa {{ content.chiffres4_icon }}"></i>
                    </div>
                    <div class="chiffres-number">
                        {{ content.chiffres4_title }}
                    </div>
                    <div class="chiffres-text">
                        {{ content.chiffres4_content }}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--div class="container">
        <section class="news main-section" id="news">
            <h2>Les dernières news</h2>
            <div class="news-subtitle">Retrouvez les dernières news sur les projet pccp</div>
            <div class="news-container">
                <div class="news-current">
                    <div class="news-current-item">
                        <div class="news-current-img"><img src="{{ url_for('static', filename='img/news.jpg') }}" alt="News"></div>
                        <div class="news-current-container">
                            <div class="news-current-title">Medic'nem</div>
                            <div class="news-current-subtitle">Rendons le nem aux vietnamiens</div>
                            <div class="news-current-date">3 septembre 2003, Paris</div>
                            <div class="news-current-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas tempora officiis beatae recusandae possimus error nisi, illum, totam fugiat, quia, repellendus perferendis! Iste dolore aspernatur voluptates, consequuntur odit repellendus culpa!</div>
                            <div class="news-current-button">
                                <a href="#">En savoir plus</a>
                            </div>
                        </div>
                    </div>
                    <div class="news-current-item">
                        <div class="news-current-img"><img src="{{ url_for('static', filename='img/news.jpg') }}" alt="News"></div>
                        <div class="news-current-container">
                            <div class="news-current-title">Medic'nem</div>
                            <div class="news-current-subtitle">Rendons le nem aux vietnamiens</div>
                            <div class="news-current-date">3 septembre 2003, Paris</div>
                            <div class="news-current-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas tempora officiis beatae recusandae possimus error nisi, illum, totam fugiat, quia, repellendus perferendis! Iste dolore aspernatur voluptates, consequuntur odit repellendus culpa!</div>
                            <div class="news-current-button">
                                <a href="#">En savoir plus</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="news-old">
                    <div class="news-old-item">
                        <div class="news-old-img">
                            <img src="{{ url_for('static', filename='img/side news image.jpg') }}" alt="">
                        </div>
                        <div class="news-old-content">
                            <div class="news-old-title">Medic'Nam trouve son assistant</div>
                            <div class="news-old-text">Un vietnamien est salarié pour effectuer les démarches sur place.</div>
                        </div>
                    </div>
                    <div class="news-old-item">
                        <div class="news-old-img">
                            <img src="{{ url_for('static', filename='img/side news image.jpg') }}" alt="">
                        </div>
                        <div class="news-old-content">
                            <div class="news-old-title">Medic'Nam trouve son assistant</div>
                            <div class="news-old-text">Un vietnamien est salarié pour effectuer les démarches sur place.</div>
                        </div>
                    </div>
                    <div class="news-old-item">
                        <div class="news-old-img">
                            <img src="{{ url_for('static', filename='img/side news image.jpg') }}" alt="">
                        </div>
                        <div class="news-old-content">
                            <div class="news-old-title">Medic'Nam trouve son assistant</div>
                            <div class="news-old-text">Un vietnamien est salarié pour effectuer les démarches sur place.</div>
                        </div>
                    </div>
                    <div class="news-old-item">
                        <div class="news-old-img">
                            <img src="{{ url_for('static', filename='img/side news image.jpg') }}" alt="">
                        </div>
                        <div class="news-old-content">
                            <div class="news-old-title">Medic'Nam trouve son assistant</div>
                            <div class="news-old-text">Un vietnamien est salarié pour effectuer les démarches sur place.</div>
                        </div>
                    </div>
                    <div class="more-old-news">
                        <a href="#">Plus ancien</a>
                    </div>
                </div>
            </div>
            <div class="more-old-news-mobile">
                <a href="#">Plus ancien</a>
            </div>
        </section>
    </div-->
    <!--section class="partenaires main-section" id="partenaires">
        <div class="container">
            <h2>NOS PARTENAIRES</h2>
            <div class="partenaires-subtitle">Sans eux, les équipes de PC Coup d'Pouce  ne pourraient pas mener à bien leurs projets !</div>
            <div class="partenaires-container">
                <div class="partenaires-item">
                    <div class="partenaires-img">
                        <img src="{{ url_for('static', filename='img/espci.png') }}" alt="">
                    </div>
                    <div class="partenaires-name">ESPCI</div>
                </div>
                <div class="partenaires-item">
                    <div class="partenaires-img">
                        <img src="{{ url_for('static', filename='img/espci.png') }}" alt="">
                    </div>
                    <div class="partenaires-name">ESPCI</div>
                </div>
            </div>
        </div>
    </section-->
</main>
{% endblock %}